apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: message

  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: message
          value: '$(params.message)'

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: branch
      default: 'main'
    - name: repo-url

  tasks:
    - name: clone
      taskRef:
        name: checkout

      params:
        - name: branch
          value: '$(params.branch)'
        - name: repo-url
          value: '$(params.repo-url)'

    - name: lint
      taskRef:
        name: echo
      params:
        - name: message
          value: 'Calling Flake8 linter…'
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: echo
      params:
        - name: message
          value: 'Running unit tests with PyUnit…'
      runAfter:
        - lint

    - name: build
      taskRef:
        name: echo
      params:
        - name: message
          value: 'Building image for $(params.repo-url) …'
      runAfter:
        - tests

    - name: deploy
      taskRef:
        name: echo
      params:
        - name: message
          value: 'Deploying $(params.branch) branch of $(params.repo-url) …'
      runAfter:
        - build
